services:
  # Seu script de monitoramento atual
  monitoramento-memoria:
    build: .
    volumes:
      - ./backups:/app/backups
    restart: always

  # Novo servi√ßo: Portainer (Dashboard Visual)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/var/data

volumes:
  portainer_data: